### ISSUE TITLE
Time format error? 

### ISSUE THREAD

**Issue by andreaponza** [A3M4/YouTube-Report#15]
Generating Heat Map.....
Traceback (most recent call last):
  File "/home/server/Scrivania/Personal-YouTube-PDF-Report-Generator/report.py", line 252, in <module>
    visual.heat_map()
  File "/home/server/Scrivania/Personal-YouTube-PDF-Report-Generator/report.py", line 46, in heat_map
    Mon = html.dataframe_heatmap('Mon')
  File "/home/server/Scrivania/Personal-YouTube-PDF-Report-Generator/parse.py", line 97, in dataframe_heatmap
    times = self.find_times()
  File "/home/server/Scrivania/Personal-YouTube-PDF-Report-Generator/parse.py", line 52, in find_times
    dayOfWeek = datetime.datetime.strptime(time[0:12], '%b %d, %Y').strftime('%a')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'Dec 15, 2019' does not match format '%b %d, %Y'

**Comment by JHJohny** [comment]
Hi,
Similar issue #26 (your is older)
I have same date format, author probably meanwhile added support for different date formats.
Could you please try again.
