### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by R3tr0BoiDX** [A3M4/YouTube-Report#21]
seaborn uses tkinter, which I dont have (and probably won't need for this)

`Traceback (most recent call last):
  File "report.py", line 5, in <module>
    import seaborn as sns
  File "C:\Program Files\Python37\lib\site-packages\seaborn\__init__.py", line 6, in <module>
    from .rcmod import *
  File "C:\Program Files\Python37\lib\site-packages\seaborn\rcmod.py", line 5, in <module>
    from . import palettes, _orig_rc_params
  File "C:\Program Files\Python37\lib\site-packages\seaborn\palettes.py", line 12, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "C:\Program Files\Python37\lib\site-packages\seaborn\utils.py", line 11, in <module>
    import matplotlib.pyplot as plt
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\pyplot.py", line 2349, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\backends\_backend_tk.py", line 6, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'`

**Comment by joshinils** [comment]
indeed, i do get the same error-message:
<pre><font color="#55FF55"><b>nils@niels</b></font>:<font color="#5555FF"><b>~/YouTube-Report</b></font>$ python report.py
Traceback (most recent call last):
  File &quot;report.py&quot;, line 8, in &lt;module&gt;
    import matplotlib.pyplot as plt
  File &quot;/home/nils/.local/lib/python2.7/site-packages/matplotlib/pyplot.py&quot;, line 115, in &lt;module&gt;
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File &quot;/home/nils/.local/lib/python2.7/site-packages/matplotlib/backends/__init__.py&quot;, line 63, in pylab_setup
    [backend_name], 0)
  File &quot;/home/nils/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py&quot;, line 4, in &lt;module&gt;
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File &quot;/home/nils/.local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py&quot;, line 5, in &lt;module&gt;
    from six.moves import tkinter as Tk
  File &quot;/home/nils/.local/lib/python2.7/site-packages/six.py&quot;, line 203, in load_module
    mod = mod._resolve()
  File &quot;/home/nils/.local/lib/python2.7/site-packages/six.py&quot;, line 115, in _resolve
    return _import_module(self.mod)
  File &quot;/home/nils/.local/lib/python2.7/site-packages/six.py&quot;, line 82, in _import_module
    __import__(name)
  File &quot;/usr/lib/python2.7/lib-tk/Tkinter.py&quot;, line 42, in &lt;module&gt;
    raise ImportError, str(msg) + &apos;, please install the python-tk package&apos;
ImportError: No module named _tkinter, please install the python-tk package
</pre>

**Comment by joshinils** [comment]
and subsequent tries to install the suggested package also fail:
<pre><font color="#55FF55"><b>nils@niels</b></font>:<font color="#5555FF"><b>~/YouTube-Report</b></font>$ pip install python-tk
Collecting python-tk
<font color="#AA0000">Exception:</font>
<font color="#AA0000">Traceback (most recent call last):</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/basecommand.py&quot;, line 215, in main</font>
<font color="#AA0000">    status = self.run(options, args)</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/commands/install.py&quot;, line 353, in run</font>
<font color="#AA0000">    wb.build(autobuilding=True)</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/wheel.py&quot;, line 749, in build</font>
<font color="#AA0000">    self.requirement_set.prepare_files(self.finder)</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/req/req_set.py&quot;, line 380, in prepare_files</font>
<font color="#AA0000">    ignore_dependencies=self.ignore_dependencies))</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/req/req_set.py&quot;, line 554, in _prepare_file</font>
<font color="#AA0000">    require_hashes</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/req/req_install.py&quot;, line 278, in populate_link</font>
<font color="#AA0000">    self.link = finder.find_requirement(self, upgrade)</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/index.py&quot;, line 465, in find_requirement</font>
<font color="#AA0000">    all_candidates = self.find_all_candidates(req.name)</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/index.py&quot;, line 423, in find_all_candidates</font>
<font color="#AA0000">    for page in self._get_pages(url_locations, project_name):</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/index.py&quot;, line 568, in _get_pages</font>
<font color="#AA0000">    page = self._get_page(location)</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/index.py&quot;, line 683, in _get_page</font>
<font color="#AA0000">    return HTMLPage.get_page(link, session=self.session)</font>
<font color="#AA0000">  File &quot;/usr/lib/python2.7/dist-packages/pip/index.py&quot;, line 795, in get_page</font>
<font color="#AA0000">    resp.raise_for_status()</font>
<font color="#AA0000">  File &quot;/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py&quot;, line 935, in raise_for_status</font>
<font color="#AA0000">    raise HTTPError(http_error_msg, response=self)</font>
<font color="#AA0000">HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/python-tk/</font>
</pre>

**Comment by SuperSandro2000** [comment]
Did you untick tk when installing python on windows? It should be part of the standard library.

**Comment by joshinils** [comment]
no, i used ubuntu 18.04

**Comment by SuperSandro2000** [comment]
You probably want to install ``python-tk`` or ``python3-tk``. You can take a look at https://packages.ubuntu.com/eoan/python3-tk, too.

**Comment by joshinils** [comment]
i'm sorry i havent googled why i could not install  `python-tk`, `tkinter` or as you suggested `python3-tk` using _`pip`_ or _`pip3`_, using `sudo apt install python-tk` worked.

but now i still have another isse (#29), but this one is closed for me.
