### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by aabacchus** [A3M4/YouTube-Report#24]
Traceback (most recent call last):
  File "report.py", line 8, in <module>
    from parse import *
  File "\~/YouTube-Report/parse.py", line 17, in <module>
    class HTML:
  File "\~/YouTube-Report/parse.py", line 19, in HTML
    htmlWatch = open(watchHistory, 'r', encoding='utf-8').read()
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by aabacchus** [comment]
Forget that, my command was "python report.py"
it should be "python3 report.py"

**Comment by aabacchus** [comment]
A few of these issues would be solved by using pip3 and python3, maybe change the readme?
