### ISSUE TITLE
UnknownTimeZoneError: 'IST'

### ISSUE THREAD

**Issue by sipah00** [A3M4/YouTube-Report#37]
while running `python report.py` I got this error
```
(free) ➜  YouTube-Report git:(master) python report.py
Generating Heat Map.....
Traceback (most recent call last):
  File "report.py", line 533, in <module>
    visual.heat_map()
  File "report.py", line 46, in heat_map
    Mon = html.dataframe_heatmap(0)
  File "/home/sipah00/YouTube-Report/parse.py", line 145, in dataframe_heatmap
    times = self.find_times()
  File "/home/sipah00/YouTube-Report/parse.py", line 82, in find_times
    times+=self.raw_find_times(*translation)
  File "/home/sipah00/YouTube-Report/parse.py", line 90, in raw_find_times
    times.append(pytz.timezone(time[-1]).localize(datetime.datetime.strptime(timegex%(time[:-1]),timegex2)))
  File "/home/sipah00/.local/lib/python3.6/site-packages/pytz/__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'IST'
```

**Comment by SuperSandro2000** [comment]
Try upgrading tzdata and reinstalling pytz.
