### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by Halikular** [A3M4/YouTube-Report#7]
This is the output when running the python script report.py on linux. May it be a font issue. I'm running Arch Linux hence all the common fonts may not be installed?
```
[weeb@fermat Personal-YouTube-PDF-Report-Generator]$ sudo python report.py 
Generating Heat Map..... 
[] 
[] 
[] 
[] 
[] 
[] 
[] 
[[0 0 0 0 0 0 0 0 0 0 0 0] 
 [0 0 0 0 0 0 0 0 0 0 0 0] 
 [0 0 0 0 0 0 0 0 0 0 0 0] 
 [0 0 0 0 0 0 0 0 0 0 0 0] 
 [0 0 0 0 0 0 0 0 0 0 0 0] 
 [0 0 0 0 0 0 0 0 0 0 0 0] 
 [0 0 0 0 0 0 0 0 0 0 0 0]] 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root' 
findfont: Font family ['Comic Sans MS'] not found. Falling back to DejaVu 
findfont: Font family ['Comic Sans MS'] not found. Falling back to DejaVu 
findfont: Font family ['Comic Sans MS'] not found. Falling back to DejaVu 
findfont: Font family ['Comic Sans MS'] not found. Falling back to DejaVu 
Generating Word Cloud..... 
Traceback (most recent call last): 
  File "report.py", line 252, in <module> 
    visual.wordCloud() 
  File "report.py", line 95, in wordCloud 
    wordcloud = WordCloud(mask=bg, background_color="white", colormap='Set 
  File "/usr/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 619 
    return self.generate_from_text(text) 
  File "/usr/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 601 
    self.generate_from_frequencies(words) 
  File "/usr/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 433 
    self.generate_from_frequencies(dict(frequencies[:2]), 
  File "/usr/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 483 
    font = ImageFont.truetype(self.font_path, font_size) 
  File "/usr/lib/python3.8/site-packages/PIL/ImageFont.py", line 640, in t 
    return freetype(font) 
  File "/usr/lib/python3.8/site-packages/PIL/ImageFont.py", line 637, in f 
    return FreeTypeFont(font, size, index, encoding, layout_engine) 
  File "/usr/lib/python3.8/site-packages/PIL/ImageFont.py", line 185, in _ 
    self.font = core.getfont( 
OSError: cannot open resource 
```

**Comment by istrupin** [comment]
I get the same error.
